apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: registry.aliyuncs.com/google_containers/pause:3.9
        ports:
        - containerPort: 8080
        command: ["sh", "-c", "echo 'Kubernetes is working!' > /tmp/index.html && while true; do { echo -e 'HTTP/1.1 200 OK\r\nContent-Length: 22\r\n\r\nKubernetes is working!'; } | nc -l -p 8080; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort